version: "3.2"
services:
  server:
    image: shhun/kfet:server
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    volumes:
      - type: volume
        source: KfetData
        target: /data
    networks:
      - backend
  websocket:
    image: shhun/kfet:websocket
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8000:80"
    volumes:
      - type: volume
        source: KfetData
        target: /data
    networks:
      - backend
networks:
  backend:
volumes:
  KfetData:
    external:
      name: KfetData
